// Simple model class matching the "employees" table.
public class Employee {

    private int id;
    private String name;
    private String department;
    private double salary;

    public Employee(int id, String name, String department, double salary) {
        this.id = id;
        this.name = name;
        this.department = department;
        this.salary = salary;
    }

    // used when inserting a new record (id is auto-generated by MySQL)
    public Employee(String name, String department, double salary) {
        this(-1, name, department, salary);
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDepartment() {
        return department;
    }

    public double getSalary() {
        return salary;
    }

    @Override
    public String toString() {
        return String.format("ID: %-4d Name: %-15s Department: %-12s Salary: %.2f",
                id, name, department, salary);
    }
}
